const swaggerJSDoc = require('swagger-jsdoc');

const schemas = {
  SocialTeenagerProject: {
    type: 'object',
    properties: {
      X: { type: 'number' },
      Y: { type: 'number' },
      OBJECTID: { type: 'integer' },
      ID: { type: 'integer' },
      TRAEGER: { type: 'string' },
      LEISTUNGEN: { type: 'string' },
      BEZEICHNUNG: { type: 'string' },
      KURZBEZEICHNUNG: { type: 'string' },
      STRASSE: { type: 'string' },
      PLZ: { type: 'integer' },
      ORT: { type: 'string' },
      TELEFON: { type: 'string' },
      EMAIL: { type: 'string' },
      FAX: { type: 'string' },
    },
    required: ['OBJECTID', 'ID', 'BEZEICHNUNG'],
  },
  School: {
    type: 'object',
    properties: {
      X: { type: 'number' },
      Y: { type: 'number' },
      OBJECTID: { type: 'integer' },
      ID: { type: 'integer' },
      TYP: { type: 'string' },
      ART: { type: 'string' },
      STANDORT: { type: 'string' },
      BEZEICHNUNG: { type: 'string' },
      BEZEICHNUNGZUSATZ: { type: 'string' },
      KURZBEZEICHNUNG: { type: 'string' },
      STRASSE: { type: 'string' },
      PLZ: { type: 'integer' },
      ORT: { type: 'string' },
      TELEFON: { type: 'string' },
      FAX: { type: 'string' },
      EMAIL: { type: 'string' },
      PROFILE: { type: 'string' },
      SPRACHEN: { type: 'string' },
      WWW: { type: 'string' },
      TRAEGER: { type: 'string' },
      TRAEGERTYP: { type: 'string' },
      BEZUGNR: { type: 'string' },
      GEBIETSARTNUMMER: { type: 'string' },
      SNUMMER: { type: 'string' },
      NUMMER: { type: 'string' },
      GlobalID: { type: 'string' },
      CreationDate: { type: 'string', format: 'date-time' },
      Creator: { type: 'string' },
      EditDate: { type: 'string', format: 'date-time' },
      Editor: { type: 'string' },
    },
    required: ['OBJECTID', 'ID', 'BEZEICHNUNG'],
  },

  SocialChildProject: {
    type: 'object',
    properties: {
      X: { type: 'number' },
      Y: { type: 'number' },
      OBJECTID: { type: 'integer' },
      ID: { type: 'integer' },
      TRAEGER: { type: 'tring' },
      LEISTUNGEN: { type: 'tring' },
      BEZEICHNUNG: { type: 'tring' },
      KURZBEZEICHNUNG: { type: 'tring' },
      STRASSE: { type: 'tring' },
      PLZ: { type: 'integer' },
      ORT: { type: 'tring' },
      TELEFON: { type: 'tring' },
      EMAIL: { type: 'tring' },
      FAX: { type: 'tring' },
    },
    required: ['OBJECTID', 'ID', 'BEZEICHNUNG'],
  },

  Kindergarden: {
    type: 'object',
    properties: {
      X: { type: 'number' },
      Y: { type: 'number' },
      OBJECTID: { type: 'integer' },
      ID: { type: 'integer' },
      TRAEGER: { type: 'string' },
      BEZEICHNUNG: { type: 'string' },
      KURZBEZEICHNUNG: { type: 'string' },
      STRASSE: { type: 'string' },
      STRSCHL: { type: 'string' },
      HAUSBEZ: { type: 'string' },
      PLZ: { type: 'integer' },
      ORT: { type: 'string' },
      HORT: { type: 'string' },
      KITA: { type: 'string' },
      URL: { type: 'string' },
      TELEFON:{ type: 'tring' },
      FAX: { type: 'tring' },
      EMAIL: { type: 'tring' },
      BARRIEREFREI: { type: 'tring' },
      INTEGRATIV: { type: 'tring' },
    },
    required: ['OBJECTID', 'ID', 'BEZEICHNUNG'],
  },
};

module.exports = schemas;